### ISSUE TITLE
feature request: Add query timer to easily see how long query took

### ISSUE THREAD

**Issue by alanruttenberg** [YASGUI/YASGUI#56]
Sometimes I have long queries, but have to walk away. It would be nice to see how long the query took.

Thanks,
Alan

**Comment by LaurensRietveld** [comment]
Makes sense, I'll add it

**Comment by LaurensRietveld** [comment]
I've added it now, but only for the table output plugin though (this is probably the most often used plugin, and I don't want to sacrifice screen space for the other plugins)
