### ISSUE TITLE
feature request: Indication of query running when query not exposed

### ISSUE THREAD

**Issue by alanruttenberg** [YASGUI/YASGUI#57]
Typically I can have several queries going. Some take longish time. As I move to other tabs - either within YASGUI or within browser, I can't tell from a glance when my queries are done and so I land up polling. 
 
Instead, I was thinking that among tabs, the ones that had running queries could have a color or a  "*". Similarly if any of the tabs in a window has a running query, an indicator in the window title (at beginning so not off right when tabs are small). Again "*" would do.

Thanks,
Alan

**Comment by LaurensRietveld** [comment]
I tried triggering the native browser loader a while ago on query time. It is possible (e.g. dropbox and gmail do this), but its extremely ugly.
However, showing this on a tab level is something that's pretty easy. I'll add that one

**Comment by alanruttenberg** [comment]
Not sure what you mean by triggering the native browser loader?

I meant something like:
first query starts to run: document.title="(running) "+document.title
last query ends: document.title.replace(/\(running\) /,"")

**Comment by LaurensRietveld** [comment]
I mean the browser loader (in chrome it's a spinner animation) visible in
the title bar when opening a page (often visible for just a few
milliseconds)

**Comment by alanruttenberg** [comment]
Got it. Yes, that would be fancy, but not worth the effort :)

**Comment by LaurensRietveld** [comment]
I've added a spinner icon for each tab. About changing the title: I've decided to avoid that, as I'd like to avoid changing things on a page outside of the YASGUI scope (such as the window title). I did make this easier by adding two events: `yasgui.on('query',....)` and `yasgui.on('queryFinish',...)` should make it easy to update the title whenever a (can be more than 1) query is running
