### ISSUE TITLE
download button not enabled

### ISSUE THREAD

**Issue by alanruttenberg** [YASGUI/YASGUI#61]
You can see this on yasgui.org - run the default query and the download button is still greyed out. Switch to raw response and back to table and it is enabled now.

**Comment by LaurensRietveld** [comment]
perhaps related to https://github.com/YASGUI/YASR/issues/75

**Comment by LaurensRietveld** [comment]
This is fixed now as well (see https://github.com/YASGUI/YASR/issues/76)
