### ISSUE TITLE
Current npm version does not install

### ISSUE THREAD

**Issue by ktk** [YASGUI/YASGUI#63]
Hi,

I can't seem to get version 1.1.10 or the 1.0.* version to install right now, neither on a Mac nor on a Linux box. It seems to fail in microtime compilation.

Gist with the log of `npm install`: https://gist.github.com/ktk/53bd664ecf023f929148

**Comment by alanruttenberg** [comment]
You could have a look at my fork https://github.com/alanruttenberg/YASGUI - I also had some installation problems and updated some components.

**Comment by ktk** [comment]
Thanks, could you do a pull-request to the original repository for this? Would make it easier to merge it.

**Comment by LaurensRietveld** [comment]
A bit of a delayed response (holidays):

Strange, I couldnt reproduce this issue. I remember there was an issue with microtime before (see https://github.com/YASGUI/YASGUI/issues/54), but that one is resolved now.

@ktk: What node version and what OS do you use?

**Comment by ktk** [comment]
@LaurensRietveld yes sorry forgot to mention that. I didn't notice it first, it seems to be a problem with Node 0.12.x but not with 0.10.x.

**Comment by LaurensRietveld** [comment]
I've updated to node 0.12.x but did not encounter issues here. Are you working on a clean checked-out version of YASGUI (and YASQE/YASR)?

**Comment by ktk** [comment]
Interesting it looks like git builds but npm does not. Did you try `npm install yasgui`?

**Comment by LaurensRietveld** [comment]
ha, thanks for catching that one. I simply did not publish YASGUI to npm after resolving #54. I just published a new version to npm, could you try again?

**Comment by ktk** [comment]
That did the trick, thanks a lot!
