### ISSUE TITLE
CORS enabled, valid query... but empty response

### ISSUE THREAD

**Issue by ColinMaudry** [YASGUI/YASGUI#65]
Hello,

I have a SPARQL endpoint (Fuseki2) set up at http://www.data.maudry.com:3030/datagouvfr/sparql.

I have set up an instance of YASGUI here: http://www.data.maudry.com/query

If I run the following query on my instance, I get an empty reponse (0 byte):

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?sub ?pred ?obj
} LIMIT 10
```

 I copied the cURL equivalent (Firefox feature), run it, and it worked, as I got the JSON results back:

```
curl "http://www.data.maudry.com:3030/datagouvfr/query" -H "Host: www.data.maudry.com:3030" -H "User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0" -H "Accept: application/sparql-results+json" -H "Accept-Language: en-GB,en;q=0.5" --compressed -H "DNT: 1" -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -H "Referer: http://www.data.maudry.com/query/" -H "Origin: http://www.data.maudry.com" -H "Connection: keep-alive" -H "Pragma: no-cache" -H "Cache-Control: no-cache" --data "query=PREFIX+rdf"%"3A+"%"3Chttp"%"3A"%"2F"%"2Fwww.w3.org"%"2F1999"%"2F02"%"2F22-rdf-syntax-ns"%"23"%"3E"%"0APREFIX+rdfs"%"3A+"%"3Chttp"%"3A"%"2F"%"2Fwww.w3.org"%"2F2000"%"2F01"%"2Frdf-schema"%"23"%"3E"%"0ASELECT+*+WHERE+"%"7B"%"0A++"%"3Fsub+"%"3Fpred+"%"3Fobj+."%"0A"%"7D+"%"0ALIMIT+10"
```

The same query works on my endpoint when if I use http://legacy.yasgui.org. I'm tempted to deploy the legacy version, but I'd first like to be sure I can't use YASGUI.

Thanks.

**Comment by ColinMaudry** [comment]
I have set up CORS in Fuseki (Jetty 9) following the instructions here: http://www.w3.org/wiki/CORS_Enabled#For_Jetty_.287_and_above.29. I don't get errors in the JS console, so I assume CORS is correctly enabled.

**Comment by LaurensRietveld** [comment]
@ColinMaudry Could you try testing your YASGUI instance with the authentication on the domain itself (http://www.data.maudry.com:3030) disabled? 
I know that the sparql path itself does not require authentication, but I suspect that the basic auth is causing issues nonetheless (nothing I can't fix though).

**Comment by LaurensRietveld** [comment]
never mind: I've already fixed it

**Comment by ColinMaudry** [comment]
Hum since I opened the issue I thought that would be up to me to determine whether it's closed or not :)

But indeed it's closed. I think what solved the issue was to specify the returned headers at server level, not only the URL pattern. So, here is my CORS filter snippet, added in Fuseki2's (Jetty 9) WEB-INF/web.xml, before any other filter:

```xml
	<!-- CORS filter-->
	
  <filter>
         <filter-name>cross-origin</filter-name>
         <filter-class>org.eclipse.jetty.servlets.CrossOriginFilter</filter-class>
         <init-param>
             <param-name>allowedOrigins</param-name>
             <param-value>*</param-value>
         </init-param>
         <init-param>
             <param-name>allowedMethods</param-name>
             <param-value>GET,POST,DELETE,PUT,HEAD,OPTIONS</param-value>
         </init-param>
         <init-param>
             <param-name>allowedHeaders</param-name>
             <param-value>Accept, Origin, X-Requested-With, Content-Type, Last-Modified, Authorization</param-value>
         </init-param>
			<init-param>
				<param-name>exposedHeaders</param-name>
				<param-value>Access-Control-Allow-Origin,Access-Control-Allow-Credentials</param-value>
  </init-param>
		
     </filter>
	<filter-mapping>
     <filter-name>cross-origin</filter-name>
     <url-pattern>/*</url-pattern>
 </filter-mapping>
```
