### ISSUE TITLE
Provide a web-frontend only minimal package

### ISSUE THREAD

**Issue by ktk** [YASGUI/YASGUI#67]
Dependencies for YASGUI seem to get bigger and bigger which is not really necessary for environments which include it just as SPARQL UI. Would it be possible to have a version on NPM which just contains the bare minimum to run YASGUI on the web?

**Comment by LaurensRietveld** [comment]
Hi Adrian,

What would you consider the bare minimum?

**Comment by ktk** [comment]
I think an easy separation would be frontend & backend requirements. Express & stuff is not needed if I want to include it into my own webapp, things like gulp-express is probably not even a backend dependency but only a devDependency.

**Comment by ktk** [comment]
We only publish the "dist" folder, so ideally the package would contain everything needed for that and the devdependencies everything to build this. It would probably be enough if you separate the stuff needed for the server part from YASGUI by for example providing a yasgui-server module for that.

**Comment by ktk** [comment]
Ah I just realize that I was not really clear with what we want. The goal is to have a package which I can add to my dependencies so I can provide a YASGUI within my own webapp. See [Trifid-L](https://github.com/zazukoians/trifid-ld) for example.

**Comment by LaurensRietveld** [comment]
Makes sense, I'll see what I can do

**Comment by ktk** [comment]
Great tnx!

**Comment by LaurensRietveld** [comment]
@ktk I've move the server code to another module (see https://github.com/YASGUI/Server). Is this what you were looking for?

**Comment by ktk** [comment]
@LaurensRietveld sounds great will check it out and close the issue afterwards!

**Comment by ktk** [comment]
Got feedback that it looks good so closing this, thanks @LaurensRietveld !
