### ISSUE TITLE
wikidata endpoint does not talk to yasgui?

### ISSUE THREAD

**Issue by jneubert** [YASGUI/YASGUI#71]
When I submit a query like "https://query.wikidata.org/bigdata/namespace/wdq/sparql?query=select * where {?s ?p ?o} limit 10" to the new wikidata endpoint, I get a reasonable answer.

However, submitting the same via yasgui.org, 

http://yasgui.org/#query=PREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E+%0APREFIX+wdt%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX+wikibase%3A+%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E%0APREFIX+p%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2F%3E%0APREFIX+v%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fstatement%2F%3E%0APREFIX+q%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fqualifier%2F%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0Aselect+*%0Awhere+%7B%3Fs+%3Fp+%3Fo%7D%0Alimit+10&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fquery.wikidata.org%2Fbigdata%2Fnamespace%2Fwdq%2Fsparql&requestMethod=POST&tabTitle=Query&outputFormat=table

I receive a "Unable to get response from endpoint.".

(The issue occured at first in a custom application with YASQE/YASR, and was reproduced here for better traceability).

**Comment by LaurensRietveld** [comment]
Hi Joachim, thanks.
This issue was discussed with the wikidata people. The problem is that wikidata does not support POST requests (which is the default setting in YASGUI).
Its reported as bug here (https://phabricator.wikimedia.org/T112151). Would you mind adding a thumbs-up ('token' is what they call it in their system) to that ticket? That might increase the issue priority

**Comment by LaurensRietveld** [comment]
ah, forgot to mention. Changing the request to GET in YASGUI should solve this issue of course

**Comment by jneubert** [comment]
Thanks! I've added a token and a comment on maximum query / URL length
