### ISSUE TITLE
local deployment configuration

### ISSUE THREAD

**Issue by bertvannuffelen** [YASGUI/YASGUI#72]
Hi Laurens, 

I worked past days to configure YASGUI for a local development setup on a virtual machine containing Virtuoso. I like to share some items that might be useful for other users.

A) CORS enabling
In order to query my Virtuoso on localhost:8890 I needed to enable CORS support on the sparql endpoint of Virtuoso. More info see: http://enable-cors.org/server_virtuoso.html

B) reduction of the default list of SPARQL endpoints
It would be nice if the function  getCkanEndpoints  in endpointCombi.js is configurable with a list. I had to rewrite the list to include the localhost:8890/sparql as default.

C) ability to add pre (and/or post) information to the SPARQL query.
It would be nice if I could configure the following in yasgui-yasge/sparql.js

YASQE.getUrlArguments = function(yasqe, config) {
	var queryMode = yasqe.getQueryMode();
         /** bert - virtuoso specific **/
	var data = [{
		name: yasqe.getQueryMode(), //either 'update' or 'query'
		value: "define input:default-graph-exclude <http://www.openlinksw.com/schemas/virtrdf#>, <http://localhost:8890/DAV/>, <http://www.w3.org/2002/07/owl#>, <http://localhost:8890/sparql>, <http://www.w3.org/ns/ldp#> "+ yasqe.getValue()
	}];
 
Virtuoso allows some additional parametrization beyond the SPARQL syntax. In this case I can avoid to get the content of "system graphs".

D) It is for me unclear what the role is of the server code. It seems dangling around and I wonder if I need it on a pure local install (with no internet connection). Can you enlighten me here? 

kind regards,

Bert

**Comment by LaurensRietveld** [comment]
> Hi Laurens,

> I worked past days to configure YASGUI for a local development setup on a virtual machine containing > Virtuoso. I like to share some items that might be useful for other users.

Excellent, thanks for sharing

> B) reduction of the default list of SPARQL endpoints
> It would be nice if the function getCkanEndpoints in endpointCombi.js is configurable with a list. I had to > rewrite the list to include the localhost:8890/sparql as default.

Good point, I've added a ticket for this (#73)

> C) ability to add pre (and/or post) information to the SPARQL query.

Makes sense as well. I've added a YASQE issue for this: https://github.com/YASGUI/YASQE/issues/72

> D) It is for me unclear what the role is of the server code. It seems dangling around and I wonder if I need it on a pure local install (with no internet connection). Can you enlighten me here?

The server code is used in the following ways:
* Enable URL shortening
* Proxy server for CORS-disabled SPARQL endpoints

As you noticed, YASGUI works fine without the server-side part though. A related topic is this one #67 , to split the server and client code.
I'm short on time as I'm busy with other projects as well, so I'll have to prioritize these issues. The smaller issues (B and C) I can probably do in the next few days.

**Comment by LaurensRietveld** [comment]
I did some work on this. B Should be configurable now, and in YASQE you should be able to configure the query string before sending the ajax call. The distinction between the YASGUI client and server is now stronger as well, as they are now two different npm modules. (see above links for the related tickets)

Closing this ticket now, but thanks again for providing the feedback
