### ISSUE TITLE
Can't hide Google Charts

### ISSUE THREAD

**Issue by eformx** [YASGUI/YASGUI#74]
I am using YASGUI (love it) locally.  Downloaded from github.com/YASGUI/YASGUI and it's not clear on how to disable the Google Charts.  This is what I tried (see below) and its still there in the UI??? Is there a project that has all the js and css to support yasgui broken out, so I can tweak the interface? I want to modify the off canvas panel and add a new D3 visualization to the pivot table plugin...It looks like most of the files are in the dist folder; however I don't know what goes where...I suppose an html template with all the dependencies would be a start and I could then piece it together.Hope you can provide some guidance.Thanks,Rob

```
<script src="dist/yasgui.min.js"></script>
<script src="doc/doc.min.js"></script>
<script type="text/javascript">
    var yasgui = YASGUI(document.getElementById("showcase"), {
        sparql: {
            showQueryButton: false //this does nothing???
        },
        outputPlugins: {
            useGoogleCharts: false //this does nothing???
        }
    });
```

**Comment by LaurensRietveld** [comment]
I've updated the documentation to better reflect how to disable google charts. YASQE and YASR are still separate components in YASGUI, so you're better off changing the YASR settings using <code>YASGUI.YASR.defaults.useGoogleCharts = false</code>.

To change the code, you shouldnt look at the dist folder. In your case, you are interesting in changing the renderer right? Then the YASR component which takes care of that should be your point of entry (http://yasr.yasgui.org). To change the code, simply clone the project, modify the pivot table plugin code (in the src directory), and run `gulp serve` to automatically create the bundled files in the `dist` directory.
Good luck! And let me know if you got any other questions
