### ISSUE TITLE
persistentOptions.tabs not initialized

### ISSUE THREAD

**Issue by bergos** [YASGUI/YASGUI#8]
I get an error in this line [1], because persistentOptions.tabs is not defined. I fixed it temporary by putting the following code before the one that causes the error.

`if (!('tabs' in persistentOptions)) persistentOptions.tabs = {};`

[1] https://github.com/YASGUI/YASGUI/blob/gh-pages/src/tabManager.js#L182

**Comment by LaurensRietveld** [comment]
Thanks for report! fixed now
